
development:
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE_DBNAME'] %>
  username: <%= ENV['MYSQL_DATABASE_USER'] %>
  password: <%= ENV['MYSQL_DATABASE_PASSWORD'] %>
  adapter: mysql2
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV['MYSQL_DATABASE_HOST'] %>

test:
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE_DBNAME'] %>
  username: <%= ENV['MYSQL_DATABASE_USER'] %>
  password: <%= ENV['MYSQL_DATABASE_PASSWORD'] %>
  adapter: mysql2
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV['MYSQL_DATABASE_HOST'] %>
  
production:
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE_DBNAME'] %>
  username: <%= ENV['MYSQL_DATABASE_USER'] %>
  password: <%= ENV['MYSQL_DATABASE_PASSWORD'] %>
  adapter: mysql2
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV['MYSQL_DATABASE_HOST'] %>